.TH helios 5 2010-Jan "linux" "heatherly custom tools manual"

.SH NAME
helios-phaeton (locate) data file format and configuration

.SH SUMMARY
helios is a fast, clean, expanded, and traceable version of the classic,
well-worn, and posix-defined locate, file indexing and searching command,
with enhanced reporting, debugging, and integration points.


